apiVersion: v1
data:
  mapRoles: |
    - groups:
    - system:masters
    rolearn: arn:aws:iam::<ACCOUNT_ID>:role/UdacityFlaskDeployCBKubectlRole
    username: build   
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::101604484387:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1X9CE3UH1SWP8
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-06-06T06:39:53Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1395"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 8958836e-d05c-4884-a3e9-6aeb0f1d6bd3
